# Generated by Django 3.1.4 on 2021-01-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutData',
            fields=[
                ('NUTR_CONT3', models.CharField(max_length=50)),
                ('NUTR_CONT2', models.CharField(max_length=50)),
                ('NUTR_CONT1', models.CharField(max_length=50)),
                ('SERVING_SIZE', models.CharField(max_length=50)),
                ('MAKER_NAME', models.CharField(max_length=200)),
                ('NUTR_CONT9', models.CharField(max_length=50)),
                ('NUTR_CONT8', models.CharField(max_length=50)),
                ('FOOD_CD', models.CharField(max_length=50)),
                ('NUTR_CONT7', models.CharField(max_length=50)),
                ('NUTR_CONT6', models.CharField(max_length=50)),
                ('NUTR_CONT5', models.CharField(max_length=50)),
                ('NUTR_CONT4', models.CharField(max_length=50)),
                ('DESC_KOR', models.CharField(max_length=200)),
                ('SAMPLING_MONTH_NAME', models.CharField(max_length=200)),
                ('SUB_REF_NAME', models.CharField(max_length=200)),
                ('SAMPLING_REGION_NAME', models.CharField(max_length=200)),
                ('GROUP_NAME', models.CharField(max_length=200)),
                ('RESEARCH_YEAR', models.CharField(max_length=50)),
                ('SAMPLING_REGION_CD', models.CharField(max_length=50)),
                ('SAMPLING_MONTH_CD', models.CharField(max_length=50)),
                ('NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('SEARCH_SCORE', models.IntegerField(default=0)),
            ],
        ),
    ]
