# Generated by Django 3.1.4 on 2021-01-01 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutfood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eat_date', models.CharField(max_length=500)),
                ('eat_time', models.CharField(max_length=500)),
                ('diet', models.ManyToManyField(related_name='favs', to='nutfood.NutData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
