# Generated by Django 3.1.4 on 2021-01-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutfood', '0001_nutfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_date', models.CharField(max_length=500)),
                ('eat_time', models.CharField(max_length=500)),
                ('diet', models.ManyToManyField(related_name='favs', to='nutfood.NutData')),
            ],
        ),
    ]
